=== albim72/XML_przekrojowy_09/SCHEMA/ASPEKTY/nip.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:simpleType name="typNIP">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([0-9]{3}-[0-9]{3}-[0-9]{2}-[0-9]{2}|[0-9]{3}-[0-9]{2}-[0-9]{2}-[0-9]{3})">
            </xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="kodWaluty">
        <xsd:restriction base="xsd:string">
            <xsd:length value="3"></xsd:length>
            <xsd:pattern value="[U,S,D,P,L,N,C,H,F]{0,3}">
            </xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>
    

    <xsd:element name="firma">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="pracownik" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="imie" type="xsd:string"></xsd:element>
                            <xsd:element name="nazwisko" type="xsd:string"></xsd:element>
                            <xsd:element name="nip" type="typNIP"></xsd:element>
                            <xsd:element name="waluta" type="kodWaluty"></xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== albim72/XML_przekrojowy_09/SCHEMA/ASPEKTY/pracownik.xml
<?xml version="1.0" encoding="UTF-8"?>

<firma xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="nip.xsd">
    <pracownik>
        <imie>Jan</imie>
        <nazwisko>Kowal</nazwisko>
        <nip>987-456-78-54</nip>
    </pracownik>
    <pracownik>
        <imie>Jan</imie>
        <nazwisko>Kowal</nazwisko>
        <nip>922-45-41-233</nip>
    </pracownik>
    <pracownik>
        <imie>Jan</imie>
        <nazwisko>Kowal</nazwisko>
        <nip>9884567054</nip>
    </pracownik>
</firma>
