=== albim72/XML_przekrojowy_09/BUDOWAXML/osoba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="spisosob">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="osoba" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="nazwisko"></xsd:element>
                            <xsd:element name="imie" maxOccurs="unbounded"></xsd:element>
                            <xsd:element name="panienskie" minOccurs="0"></xsd:element>
                            <xsd:element name="dzieci" minOccurs="0" maxOccurs="unbounded"></xsd:element>
                        </xsd:sequence>
                </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
           
    </xsd:element>

    
</xsd:schema>

=== albim72/XML_przekrojowy_09/BUDOWAXML/osoba.xml
<?xml version="1.0" encoding="UTF-8"?>
<spisosob xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="osoba.xsd">
    <osoba>

        <nazwisko>Berek</nazwisko>
        <imie>Jan</imie>

    </osoba>

    <osoba>

        <nazwisko>Berek</nazwisko>
        <imie>Anna</imie>
        <panienskie>Kos</panienskie>

        
    </osoba>

    <osoba>

        <nazwisko>Kowal</nazwisko>
        <imie>Antek</imie>
        <dzieci>Jacek</dzieci>
        <dzieci>Ewa</dzieci>
        
    </osoba>

</spisosob>
