=== albim72/XML_przekrojowy_09/DTD/ucz5.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT uczelnia (nazwa, wydzial+)>
<!ELEMENT nazwa (#PCDATA)>

<!ELEMENT wydzial (#PCDATA | kierunek | instytut)*>
<!ELEMENT kierunek (#PCDATA)>
<!ELEMENT instytut (#PCDATA)>

=== albim72/XML_przekrojowy_09/DTD/uczelnia5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE uczelnia SYSTEM "ucz5.dtd">
<uczelnia>
    <nazwa>Politechnika Śląska</nazwa>
    <wydzial>
        <kierunek>Automatyka,Eletronika i Informatyka</kierunek>
        <instytut>Instytut Automatyki</instytut>
        <instytut>Instytut Elektroniki</instytut>
        <instytut>Instytut Informatyki</instytut>
        na wydziale dostępne są 3 szatnie!
    </wydzial>
    <wydzial>
        To jest Wydział Matematyki i Fizyki prowadzcy kierunek
        <kierunek>Matematyka</kierunek>
        oraz kierunek
        <kierunek>Fizyka</kierunek>
    </wydzial>
</uczelnia>
