=== albim72/XML_przekrojowy_09/SCHEMA/WARTOSCI_NIEP/uczelnia.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="uczelnia">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="listaStudentow">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="student" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="nazwisko" type="xsd:string"></xsd:element>
                                        <xsd:element name="imie" type="xsd:string"></xsd:element>
                                        <xsd:element name="nrIndeksu" type="xsd:decimal"></xsd:element>
                                        <xsd:element name="wydzialStudent" type="xsd:string"></xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="grupa" type="xsd:string"></xsd:attribute>
                                    <xsd:attribute name="pozycjaWGrupie" type="xsd:string"></xsd:attribute>
                                </xsd:complexType> 
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>

                    <!-- klucz prosty odwołanie do pola selektora (elementu nadrzędnego)-->
                    <xsd:key name="kluczStudenta">
                        <xsd:selector xpath="student"></xsd:selector>
                        <xsd:field xpath="nrIndeksu"></xsd:field>
                    </xsd:key>

                    <!-- klucz złożony o charakterze unikatowym -->
                    <xsd:unique name="kluczZlozony">
                        <xsd:selector xpath="student"></xsd:selector>
                        <xsd:field xpath="wydzialStudent"></xsd:field>
                        <xsd:field xpath="@grupa"></xsd:field>
                        <xsd:field xpath="@pozycjaWGrupie"></xsd:field>
                    </xsd:unique>

                </xsd:element>

                <xsd:element name="wydzial" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="nazwa" type="xsd:string"></xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="numerWydzialu" type="xsd:string"></xsd:attribute>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>

        <xsd:unique name="kluczNazwiskoImie">
            <xsd:selector xpath="listaStudentow/student"></xsd:selector>
            <xsd:field xpath="nazwisko"></xsd:field>
            <xsd:field xpath="imie"></xsd:field>
        </xsd:unique>

        <xsd:key name="kluczWydzial">
            <xsd:selector xpath="wydzial"></xsd:selector>
            <xsd:field xpath="@numerWydzialu"></xsd:field>
        </xsd:key>

        <xsd:keyref name="wydzStudenta" refer="kluczWydzial">
            <xsd:selector xpath="listaStudentow/student"></xsd:selector>
            <xsd:field xpath="wydzialStudent"></xsd:field>

        </xsd:keyref>


    </xsd:element>
</xsd:schema>

=== albim72/XML_przekrojowy_09/SCHEMA/WARTOSCI_NIEP/uczelnia.xml
<?xml version="1.0" encoding="UTF-8"?>

<uczelnia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="uczelnia.xsd">
    <listaStudentow>
        <student grupa="I" pozycjaWGrupie="10">
            <nazwisko>Kowalski</nazwisko>
            <imie>Jan</imie>
            <nrIndeksu>347</nrIndeksu>
            <wydzialStudent>3499</wydzialStudent>
        </student>
        <student grupa="I" pozycjaWGrupie="11">
            <nazwisko>Nowak</nazwisko>
            <imie>Anna</imie>
            <nrIndeksu>536</nrIndeksu>
            <wydzialStudent>3499</wydzialStudent>
        </student>
        <student grupa="IV" pozycjaWGrupie="2">
            <nazwisko>Leonowski</nazwisko>
            <imie>Leon</imie>
            <nrIndeksu>876</nrIndeksu>
            <wydzialStudent>3122</wydzialStudent>
        </student>
        <student grupa="I" pozycjaWGrupie="10">
            <nazwisko>Leonowski</nazwisko>
            <imie>Linus</imie>
            <nrIndeksu>832</nrIndeksu>
            <wydzialStudent>3122</wydzialStudent>
        </student>
        <student grupa="V" pozycjaWGrupie="8">
            <nazwisko>Lepek</nazwisko>
            <imie>Linus</imie>
            <nrIndeksu>811</nrIndeksu>
            <wydzialStudent>2211</wydzialStudent>
        </student>
    </listaStudentow>

    <wydzial numerWydzialu="3499">
        <nazwa>Wydział Informatyki i Zarządzania</nazwa>
    </wydzial>
    <wydzial numerWydzialu="3122">
        <nazwa>Wydział Elektroniki</nazwa>
    </wydzial>
    <wydzial numerWydzialu="2211">
        <nazwa>Wydział Archologii</nazwa>
    </wydzial>
</uczelnia>
